name: Cypress Tests

on: 
 workflow_dispatch:

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
     image: cypress/browsers:node-20.17.0-chrome-128.0.6613.119-1-ff-130.0-edge-128.0.2739.63-1
     options: --user 1001
    steps: 
     - name: get code
       uses: actions/checkout@v4.2.0

     - name: Install dependencies
       run: yarn install

     - name: Run E2E tests
       run: node runner.js



  
 